# Generated by Django 6.0.2 on 2026-02-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('cuota', 'Cuota tienda'), ('fijo', 'Pago fijo'), ('cheque', 'Cheque a fecha'), ('unico', 'Pago único')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal'), ('unico', 'Único')], max_length=20)),
                ('total_cuotas', models.PositiveIntegerField()),
                ('cuotas_restantes', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pagos.pagoprogramado')),
            ],
        ),
    ]
