# Generated by Django 6.0.2 on 2026-02-20 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='pagos.pagoprogramado')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
