# Generated by Django 6.0.2 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagoreal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, default='', max_length=80)),
                ('banco', models.CharField(blank=True, default='', max_length=80)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo / Salida'), ('abono', 'Abono / Entrada'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('hash_unico', models.CharField(max_length=64, unique=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='pagos_movim_fecha_1511ab_idx'), models.Index(fields=['monto'], name='pagos_movim_monto_7d586c_idx'), models.Index(fields=['tipo'], name='pagos_movim_tipo_e3530f_idx')],
            },
        ),
    ]
