# Generated by Django 6.0.2 on 2026-02-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_movimientobancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='conciliado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='nota_conciliacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='pago_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_conciliados', to='pagos.pagoreal'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['conciliado'], name='pagos_movim_concili_5439d7_idx'),
        ),
    ]
