# Generated by Django 6.0.2 on 2026-03-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_movimientobancario_conciliado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('hoja', models.CharField(blank=True, max_length=120)),
                ('crear_pagos_reales', models.BooleanField(default=False)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('total_deudas_creadas', models.PositiveIntegerField(default=0)),
                ('total_deudas_existentes', models.PositiveIntegerField(default=0)),
                ('total_pagos_creados', models.PositiveIntegerField(default=0)),
                ('total_pagos_existentes', models.PositiveIntegerField(default=0)),
                ('total_omitidas', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('revertida', 'Revertida')], default='confirmada', max_length=20)),
                ('revertida_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('revertida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_pagos_revertidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionPagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_registro', models.CharField(choices=[('deuda', 'Deuda creada'), ('pago_real', 'Pago real creado')], max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=180)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pagos.importacionpago')),
                ('pago_programado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_importacion', to='pagos.pagoprogramado')),
                ('pago_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_importacion', to='pagos.pagoreal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
