# Generated by Django 6.0.2 on 2026-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_importacionpago_importacionpagodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoprogramado',
            name='unidad_negocio',
            field=models.CharField(blank=True, choices=[('terminal', 'Terminal'), ('cauquenes', 'Cauquenes'), ('alerce', 'Alerce'), ('pitrufquen', 'Pitrufquén'), ('pasmar', 'Pasmar'), ('valdivia', 'Valdivia'), ('espacio_costanera', 'Espacio Costanera'), ('costanera_ampliacion', 'Costanera Ampliación'), ('mall_castro', 'Mall Castro'), ('imposiciones', 'Imposiciones'), ('iva', 'IVA'), ('otros', 'Otros')], default='otros', max_length=40, verbose_name='Unidad / lugar'),
        ),
    ]
