# Generated by Django 6.0.2 on 2026-03-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_pagoprogramado_unidad_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('legacy_key', models.CharField(blank=True, default='', max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='pagoprogramado',
            name='unidad_negocio',
            field=models.CharField(blank=True, choices=[('terminal', 'Terminal'), ('cauquenes', 'Cauquenes'), ('alerce', 'Alerce'), ('pitrufquen', 'Pitrufquén'), ('pasmar', 'Pasmar'), ('valdivia', 'Valdivia'), ('espacio_costanera', 'Espacio Costanera'), ('costanera_ampliacion', 'Costanera Ampliación'), ('mall_castro', 'Mall Castro'), ('carolina', 'Carolina'), ('oficina', 'Oficina'), ('imposiciones', 'Imposiciones'), ('iva', 'IVA'), ('vivian', 'Vivian'), ('tottus', 'Tottus'), ('otros', 'Otros')], default='otros', max_length=40, verbose_name='Unidad / lugar'),
        ),
        migrations.AddField(
            model_name='pagoprogramado',
            name='unidad_negocio_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_programados', to='pagos.unidadnegocio', verbose_name='Unidad / lugar'),
        ),
    ]
