# Generated by Django 6.0.2 on 2026-04-04 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_unidadnegocio_alter_pagoprogramado_unidad_negocio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('nombre_empresa', models.CharField(default='Mi empresa', max_length=160)),
                ('razon_social', models.CharField(blank=True, default='', max_length=180)),
                ('rut', models.CharField(blank=True, default='', max_length=20)),
                ('giro', models.CharField(blank=True, default='', max_length=180)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('direccion', models.CharField(blank=True, default='', max_length=220)),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('logo', models.FileField(blank=True, help_text='Formatos permitidos: PNG, JPG, JPEG, SVG o WEBP.', null=True, upload_to='empresa/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Logo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuración de empresa',
                'ordering': ['id'],
            },
        ),
    ]
