# Generated by Django 6.0.2 on 2026-04-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_categoria_recurrente_parametrizable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoprogramado',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('anular', 'Anular'), ('eliminar', 'Eliminar'), ('activar', 'Activar'), ('desactivar', 'Desactivar'), ('importar', 'Importar'), ('revertir_importacion', 'Revertir importación'), ('conciliar', 'Conciliar'), ('desconciliar', 'Desconciliar'), ('regenerar', 'Regenerar'), ('otro', 'Otro')], default='otro', max_length=40)),
                ('modulo', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=64)),
                ('objeto_repr', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, default='', max_length=255)),
                ('metodo_http', models.CharField(blank=True, default='', max_length=10)),
                ('es_critico', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-creado', '-id'],
                'indexes': [models.Index(fields=['-creado'], name='pagos_regis_creado_81bc0a_idx'), models.Index(fields=['accion'], name='pagos_regis_accion_0e360d_idx'), models.Index(fields=['modulo'], name='pagos_regis_modulo_f4011d_idx'), models.Index(fields=['modelo'], name='pagos_regis_modelo_fc7606_idx')],
            },
        ),
    ]
